# WeatherControl's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

disableSnowForm: false # Prevent snow from being placed by the environment
disableIceForm: false # Prevent ice from being placed by the environment

interval:
    enable: false # Enable interval.
    showMessages: true # Enable or disable interval messages.
    weatherLength: 120 # This is the length of weather, deafult 120 seconds.
    weatherInterval: 600 # This is the time between each weather, default 10 minutes.
    thunderLength: 30 # This is the length of weather, default 30 seconds.
    thunderInterval: 60 # This is the time between each thunder, default 60 seconds.

weather:
    enable: true # Enable weather.

thunder:
    enable: true # Enable thunder.

lightning:
    enable: true # Enable lightning strike.

    explosion: false # Enable TNT-like explosion on lightning strike.
    wand: 348 # Define the wand item.
    count: 1 # Default count of lightning per strike.
    distance: 10 # Default distance for strikemob command.

    disableChargedCreeper: false # Disable charged creepers.
    disablePigZap: false # Disable pig zapping (turning into zombie pigmen).
    disableStrikePlayerDamage: false # Prevent players from being damaged by lightning strikes.
    disableStrikeMobDamage: false # Prevent mobs from being damaged by lightning strikes.
    disableStrikeFire: false # Prevent lightning strike from causing fire.

