# WeatherControl's configuration file.

messages:
    It_is_thundering: "It's thundering."
    It_is_storming: "It's storming."
    It_is_clear: "It's clear."

    It_will_storm_for_another: "It will storm for another <duration>."
    It_will_now_storm_for: "It will now storm for <duration>."
    It_is_no_longer_storm: "It's no longer storm."
    It_is_no_active_storm: "It's no active storm!"
    Weather_is_disabled: "Weather is disabled!"

    It_will_thunder_for_another: "It will thunder for another <duration>."
    It_will_now_thunder_for: "It will now thunder for <duration>."
    It_is_no_longer_thunder: "It's no longer thunder."
    It_is_no_active_thunder: "It's no active thunder."
    Thunder_is_disabled: "Thunder is disabled!"
    
    It_is_now_clearing: "It's now clearing."
    It_is_already_clear: "It's already clear."
    
    You_have_been_struck_by_lightning: "You have been struck by lightning!"
    Player_have_been_struck_by_lightning: "Player <player> have been struck by lightning."
    Have_been_struck_by_lightning: "<count> <entity> have been struck by lightning!"
    Player_does_not_exist: "Player does not exist!"
    Lightning_is_disabled: "Lightning is disabled!"
    Position_has_been_struck_by_lightning: "Position <location> have been struck by lightning!"
    You_have_to_specify_a_valid_position: "You have to specify a valid position!"
    You_got_the_lightning_strike_wand: "You got the lightning strike wand."
    Maximum_wand_count_is: "Maximum wand count is <maxcount>."
    Wand_count_set_to: "Wand count set to <count>."

    Wand_not_set_in_configuration_file: "Wand not set in configuration file!"