# WeatherControl's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

weather:
    enable: true # Enable weather.
    interval: 0
    
thunder:
    enable: true # Enable thunder.
    interval: 0 
    
lightning:
    enable: true # Enable lightning strike.
    wand: 348
    distance: 10 # Default distance for strikemob command.
    
    disableCreeperPower: false # Disable creeper power.
    disablePigZap: false # Disable pig zap.
    disableLightningStrikePlayerDamage: false # Prevent players to be damaged by lightning stirke.
    disableLightningStrikeMobDamage: false # Prevent mobs to be damaged by lightning stirke.
    disableLightningStrikeFire: false # Prevent lightning strike to cause fire.