# WeatherControl's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

disableSnowForm: false # Prevent snow to be placed by the enviroment

weather:
    enable: true # Enable weather.
    
thunder:
    enable: true # Enable thunder.
    
lightning:
    enable: true # Enable lightning strike.
    
    wand: 348 # Define the wand item.
    count: 1 # Default count of lightning per strike.
    
    distance: 10 # Default distance for strikemob command.
    
    disableCreeperPower: false # Disable creeper power.
    disablePigZap: false # Disable pig zap.
    disableLightningStrikePlayerDamage: false # Prevent players to be damaged by lightning stirke.
    disableLightningStrikeMobDamage: false # Prevent mobs to be damaged by lightning stirke.
    disableLightningStrikeFire: false # Prevent lightning strike to cause fire.