# WeatherControl's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

weather:
    defaultWeatherDuration: 300 # Default 5 minutes (300 secounds).
    disableWeather: false # Disable weather.
    
thunder:
    defaultThunderDuration: 300 # Default 5 minutes (300 secounds).
    disableThunder: false # Disable thunder.
    
lightning:
    lightningStrikeWand: true 
    lightningStrikeWandItem: 348
    disableLightningStrike: false # Disable lightning strike.
    disableCreeperPower: false # Disable creeper power.
    disablePigZap: false # Disable pig zap.
    disableLightningStrikeDamage: false # Prevent players to be damaged by lightning stirke.
    disableLightningStrikeFire: false # Prevent lightning strike to cause fire.