# WeatherControl's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

clickLightningStrike: true
clickLightningStrikeItem: 348

weather:
    # Default 5 minutes (300 secounds)
    defaultWeatherDuration: 300

lightning:
    disableLightningStrikeDamage: false
    disableLightningStrikeFire: false