# WeatherControl's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

weather:
    enable: true # Enable weather.
    defaultWeatherDuration: 300 # Default 5 minutes (300 secounds).
    
thunder:
    enable: true # Enable thunder.
    defaultThunderDuration: 300 # Default 5 minutes (300 secounds).
    
lightning:
    enable: true # Enable lightning strike.
    
    lightningStrikeWand: true # Enable wand to strike lightning.
    lightningStrikeWandItem: 348 # Wand item.
    lightningStrikeWandMultiCount: 5 # Multi lightning strike count.
    lightningLightningStrikeDistance: 10 # Default distance for strike command.
    
    disableCreeperPower: false # Disable creeper power.
    disablePigZap: false # Disable pig zap.
    disableLightningStrikePlayerDamage: false # Prevent players to be damaged by lightning stirke.
    disableLightningStrikeMobDamage: false # Prevent mobs to be damaged by lightning stirke.
    disableLightningStrikeFire: false # Prevent lightning strike to cause fire.